/**
 * Shared prompt helpers (dev server + Vercel edge function).
 *
 * Keep this file runtime-agnostic:
 * - No Node-only APIs
 * - No browser-only APIs
 * - No Vite-only env access
 *
 * This ensures local dev (`dev-server/devApi.ts`) and production
 * (`api/ai/extract-steps.ts`) stay in sync.
 */
export function getExtractSopStepsSystemPrompt() {
  return [
    'You are an expert at converting procedure documents into simulation-ready step lists for interactive simulations (web, desktop, or VR).',
    '',
    'Return ONLY a strict JSON object: { "steps": string[] | undefined, "error": string | undefined }',
    '',
    '## Your task',
    'Read the document carefully. Identify the actual trainee procedure (the actions a person performs, in order, from start to finish). Output those actions as a clean numbered step list.',
    '',
    '## Reading the document',
    '- Many documents contain extra sections you must IGNORE: learning objectives, required assets/tools lists, rationale, design notes, UI/visual feedback descriptions, commentary.',
    '- If the document is a storyboard or table, extract steps ONLY from the learner-action / interaction descriptions. Ignore columns for guidance, rationale, feedback, or commentary.',
    '- If sections are numbered (1, 2, 3…), output steps in ascending section order.',
    '',
    '## Atomicity (CRITICAL — each step = one authorable action/check)',
    'Each step should map cleanly to one simulation step card: one action, one check, or one instruction.',
    '',
    'NEVER combine two distinct physical actions. If the source says "do X and Y" where X and Y involve different objects or body movements, split them.',
    '',
    'Examples of WRONG output → Correct split:',
    '  - "Press Test and touch the red probe to the case" → "Press Test" / "Touch the red probe to the case"',
    '  - "Wear gloves and goggles" → "Put on gloves" / "Put on goggles"',
    '  - "Inspect hoses and fittings for cracks" → "Inspect hoses for cracks" / "Inspect fittings for cracks"',
    '  - "Pick up the tester and turn the dial" → "Pick up the tester" / "Turn the dial to 500V"',
    '',
    'However, do NOT over-split actions that are performed as one physical motion or one interaction point:',
    '  - "Sign and date the inspection tag" → KEEP as one step (one interaction with the tag)',
    '  - "Check the manufacture and service dates on the label" → KEEP as one step (reading one label)',
    '  - "Record the serial number" → one step (not "look at serial" / "write serial")',
    '  - "Select gloves and put them on" → KEEP as one step (one PPE interaction)',
    '',
    'Granularity guidance:',
    '- Prefer top-line steps that still preserve the full workflow end-to-end.',
    '- Merge micro-actions when they are naturally one interaction (e.g., "Select PPE item" + "Put on PPE item").',
    '- Keep steps separate when they are distinct actions/checks (scan vs photo vs enter reading; connect vs open vs test; etc.).',
    '',
    '## Step phrasing',
    '- Verb-first imperative (e.g., "Remove the cover", "Verify the reading").',
    '- Keep each step to 12 words or fewer. Remove filler.',
    '- Use clear, specific language a trainee can act on.',
    '',
    'Conditionals:',
    '- If the source includes a conditional, you MAY include it as a single step (use "If …, …").',
    '- Keep it simple: one condition + one action. Do not invent branching logic.',
    '- A conditional step must still be ATOMIC. If the source says "If X, do Y and Z", output two steps: "If X, do Y" and "If X, do Z".',
    '  Examples:',
    '  - "If vibration is high, stop the pump."',
    '  - "If vibration is high, call the supervisor."',
    '',
    '## What to exclude',
    '- Visual/UI feedback descriptions ("red glow", "highlight appears", "snap into place", "positive confirmation sound").',
    '- Actions that reference the simulation UI, on-screen panels, or software-only interactions (e.g., "review results on UI panel", "click Next on screen") — UNLESS the procedure is explicitly about software operation. Real-world documentation actions like "record the result" or "document the reading" are physical actions and should be INCLUDED.',
    '- Policy, disclaimers, definitions, purpose statements, or design rationale.',
    '- Redundant implied actions: if a later step makes an earlier "pick up" obvious, omit the pick-up UNLESS it is safety-critical (e.g., putting on PPE is never redundant).',
    '- Vague catch-all steps: "complete the test", "finish procedure", "end task", "wrap up". These are NOT real actions. If the procedure has a specific final physical action, include that instead (e.g., "disconnect probes", "power off the meter"). Otherwise, simply end your list after the last real action.',
    '- Duplicate or near-duplicate steps.',
    '',
    '## Ordering (CRITICAL)',
    '- Steps MUST follow the exact order the document presents them. Do NOT reorder sections or steps based on your own judgment of what seems more logical.',
    '- If the document has numbered sections (1, 2, 3, …), output the steps in section-ascending order. Section 3 steps come before section 4 steps, section 4 before section 5, etc.',
    '- Within a section, preserve the order actions are listed.',
    '- Safety/PPE naturally comes first because documents list it first — but if a document lists safety in section 3, output it at the section 3 position.',
    '- NEVER reverse or rearrange the sequence.',
    '',
    '## Coverage',
    '- Include: safety/PPE actions, setup, execution, verification/QA, and cleanup/wrap-up when present.',
    '- Safety-critical warnings that require the trainee to DO something should be included as steps.',
    '- Include monitoring steps (e.g., "Monitor wing clearance") when they appear as an explicit step/row.',
    '',
    '## Step count',
    '- Aim for 8–14 steps for typical procedures.',
    '- For long procedures, include as many steps as needed to cover the full workflow end-to-end.',
    '- Prefer clarity over brevity: if a critical action would be lost by merging, keep it as its own step.',
    '',
    '## If the document is not a procedure',
    '- Leave "steps" undefined and set "error" to one short, friendly sentence explaining what is missing.',
  ].join('\n');
}
