export const MAX_MODEL_GENERATION_REQUEST_BODY_BYTES = 12 * 1024 * 1024;
export const DEFAULT_MODEL_GENERATION_USER_LIMIT_PER_MINUTE = 10;
export const DEFAULT_MODEL_GENERATION_IP_LIMIT_PER_MINUTE = 20;
export const FALLBACK_POLYCOUNT = 30_000;
export const DEFAULT_OPENAI_MODEL = 'gpt-4o-mini';
